### PR TITLE
Fix errors when not installed in root dir

### LINKED ISSUE #148: PrettyGCode does not work behind proxy
PrettyGCode is failing to work behind a reverse proxy (nginx) because it's not using the right URLs. All other plugins and OctoPrint itself work fine.
image
I have nginx adding these headers which should be plenty:
```
Host: <actual hostname>
X-Real-IP: <real client IP>
X-Forwarded-For: <client IP>, <proxy IP>
X-Scheme: https
X-Script-Name: /ender3v2
```
Again, other plugins and OctoPrint itself seem to pick up on this, and they use the correct URLs. But PrettyGCode does not.

### PR DESCRIPTION
**Pull request by tyrel**
Use relative paths instead of absolute paths so that if OctoPrint is not in the root of the domain (or is behind a proxy), the files can still be found and this plugin will work.

Fixes #148

### CODE REVIEW

**Comment by jneilliii** [comment]
Funny, same as my submission #147

File: octoprint_prettygcode/static/js/prettygcode.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ $(function () {
                 durJobDate = job.file.date;
                 if(viewInitialized && gcodeProxy)
                     {
-                        gcodeProxy.loadGcode('/downloads/files/local/' + curJobName);
+                        gcodeProxy.loadGcode('downloads/files/local/' + curJobName);
```
Comment (jotadrilo) [inline octoprint_prettygcode/static/js/prettygcode.js:19]: OctoPrint defines the `BASEURL` global variable available to all plugins:

```suggestion
                        gcodeProxy.loadGcode(BASEURL + 'downloads/files/local/' + curJobName);
```

File: octoprint_prettygcode/static/js/prettygcode.js [hunk 2]
```diff
@@ -569,7 +569,7 @@ $(function () {
             this.orbitWhenIdle=false;
             this.reloadGcode = function () {
                 if(gcodeProxy && curJobName!="")
-                    gcodeProxy.loadGcode('/downloads/files/local/' + curJobName);  
+                    gcodeProxy.loadGcode('downloads/files/local/' + curJobName);
```
Comment (jotadrilo) [inline octoprint_prettygcode/static/js/prettygcode.js:572]:
```suggestion
                    gcodeProxy.loadGcode(BASEURL + 'downloads/files/local/' + curJobName);  
```

File: octoprint_prettygcode/static/js/prettygcode.js [hunk 3]
```diff
@@ -692,7 +692,7 @@ $(function () {
 
                     //load Nozzle model.
                     var objloader = new THREE.OBJLoader();
-                    objloader.load( '/plugin/prettygcode/static/js/models/ExtruderNozzle.obj', function ( obj ) {
+                    objloader.load( 'plugin/prettygcode/static/js/models/ExtruderNozzle.obj', function ( obj ) {
```
Comment (jotadrilo) [inline octoprint_prettygcode/static/js/prettygcode.js:695]:
```suggestion
                    objloader.load( BASEURL + 'plugin/prettygcode/static/js/models/ExtruderNozzle.obj', function ( obj ) {
```

File: octoprint_prettygcode/static/js/prettygcode.js [hunk 4]
```diff
@@ -721,7 +721,7 @@ $(function () {
                     scene.add(gcodeObject);
 
                     if(curJobName!="")
-                        gcodeProxy.loadGcode('/downloads/files/local/' + curJobName);
+                        gcodeProxy.loadGcode('downloads/files/local/' + curJobName);
```
Comment (jotadrilo) [inline octoprint_prettygcode/static/js/prettygcode.js:724]:
```suggestion
                        gcodeProxy.loadGcode(BASEURL + 'downloads/files/local/' + curJobName);
```

File: octoprint_prettygcode/static/js/prettygcode.js [hunk 5]
```diff
@@ -1533,7 +1533,7 @@ $(function () {
             }
 
             var fontLoader = new THREE.FontLoader();
-            fontLoader.load('/plugin/prettygcode/static/js/helvetiker_bold.typeface.json', function (font) {
+            fontLoader.load('plugin/prettygcode/static/js/helvetiker_bold.typeface.json', function (font) {
```
Comment (jotadrilo) [inline octoprint_prettygcode/static/js/prettygcode.js:1536]:
```suggestion
            fontLoader.load(BASEURL + 'plugin/prettygcode/static/js/helvetiker_bold.typeface.json', function (font) {
```

**Comment by jotadrilo** [comment]
I have added the same comments in both PRs. I'd suggest closing one of them

File: octoprint_prettygcode/static/js/prettygcode.js (hunk 1 above)
Comment (jneilliii) [reply octoprint_prettygcode/static/js/prettygcode.js:19]: I'm their that's what my change should do, no need to add base url for actual relative links.
